export const products2 = [
  {
    id: '1',
    image: require('../assets/images/D1.png'),
    name: `IWC Schaffhausen
2021 Pilot's Watch "SIHH 2019" 44mm`,
    price: 1500,
    oldPrice: 2499,
    discount: '40%Off',
    rating: 4,
    reviews: 56890,
  },
  {
    id: '2',
    image: require('../assets/images/D2.png'),
    name: 'Labbin White Sneakers For Men and Female',
    price: 2499,
    oldPrice: 4999,
    discount: '50%Off',
    rating: 4,
    reviews: 344657,
  },
  {
    id: '3',
    image: require('../assets/images/D3.png'),
    name: `Mammon Women's Handba (Set of 3, Beige)`,
    price: 999,
    oldPrice: 1999,
    discount: '50%Off',
    rating: 5,
    reviews: 646776,
  },
  {
    id: '4',
    image: require('../assets/images/D4.png'),
    name: 'Do Bhai Women Wedges Sandal (Butterfly)',
    price: 1500,
    oldPrice: 3500,
    discount: '60%Off',
    rating: 4,
    reviews: 15007,
  },
  {
    id: '5',
    image: require('../assets/images/D5.png'),
    name: 'Lakme Enrich Matte Lipstick - Shade RM1(4.7gm)',
    price: 1500,
    oldPrice: 3500,
    discount: '60%Off',
    rating: 4,
    reviews: 15007,
  },
  {
    id: '6',
    image: require('../assets/images/D6.png'),
    name: 'Mens Starry',
    price: 399,
    oldPrice: 900,
    discount: '60%Off',
    rating: 4,
    reviews: `1,52,344`,
  },
  {
    id: '7',
    image: require('../assets/images/D7.png'),
    name: 'D7200 Digital C...',
    price: 26999,
    oldPrice: 85000,
    discount: '50%Off',
    rating: 4,
    reviews: 15007,
  },
  {
    id: '8',
    image: require('../assets/images/D8.png'),
    name: 'Jordan Stay',
    price: 4999,
    oldPrice: 8999,
    discount: '60%Off',
    rating: 4,
    reviews: `1,52,344`,
  },
  {
    id: '9',
    image: require('../assets/images/D9.png'),
    name: 'Realme 7 ',
    price: 13000,
    oldPrice: 18000,
    discount: '60%Off',
    rating: 4,
    reviews: 15007,
  },
  {
    id: '10',
    image: require('../assets/images/D10.png'),
    name: 'Flare Dress',
    price: 1900,
    oldPrice: 2500,
    discount: '60%Off',
    rating: 4,
    reviews: `1,52,344`,
  },
  {
    id: '11',
    image: require('../assets/images/D11.png'),
    name: 'Black Winter...',
    price: 499,
    oldPrice: 899,
    discount: '60%Off',
    rating: 4,
    reviews: `1,52,344`,
  },
  {
    id: '12',
    image: require('../assets/images/D12.png'),
    name: 'Pink Embroide...',
    price: 1900,
    oldPrice: 2500,
    discount: '60%Off',
    rating: 4,
    reviews: `1,52,344`,
  },
  {
    id: '13',
    image: require('../assets/images/D13.png'),
    name: 'men’s & boys s...',
    price: 999,
    oldPrice: 1499,
    discount: '60%Off',
    rating: 4,
    reviews: `1,52,344`,
  },
  {
    id: '14',
    image: require('../assets/images/unsplash.png'),
    name: 'NIke Sneakers',
    description: 'Mid Peach Mocha Shoes For Man White Black Pink S...',
    price: 1900,
    oldPrice: 2499,
    discount: '40%Off',
    rating: 4,
    reviews: 56890,
  },
  {
    id: '15',
    image: require('../assets/images/image1.png'),
    name: 'TITAN Men Watch-1806N',
    description:
      'This Titan watch in Black color is I wanted to buy for a long time',
    price: 1500,
    oldPrice: 2499,
    discount: '40%Off',
    rating: 4,
    reviews: 56890,
  },
  {
    id: '16',
    image: require('../assets/images/image2.png'),
    name: 'HRX by Hrithik Roshan',
    description: 'Neque porro quisquam est qui dolorem ipsum quia',
    price: 2499,
    oldPrice: 4999,
    discount: '50%Off',
    rating: 4,
    reviews: 344657,
  },
  {
    id: '17',
    image: require('../assets/images/image3.png'),
    name: 'Philips BHH880/10',
    description:
      'Hair Straightening Brush With Keratin Infused Bristles (Black)',
    price: 999,
    oldPrice: 1999,
    discount: '50%Off',
    rating: 5,
    reviews: 646776,
  },
  {
    id: '18',
    image: require('../assets/images/image4.png'),
    name: 'Women Printed Kurta',
    description: 'Neque porro quisquam est qui dolorem ipsum quia',
    price: 1500,
    oldPrice: 3500,
    discount: '60%Off',
    rating: 4,
    reviews: 15007,
  },
  {
    id: '19',
    image: require('../assets/images/MaskGroup.png'),
    name: `IWC Schaffhausen
2021 Pilot's Watch "SIHH 2019" 44mm`,
    price: 1500,
    oldPrice: 2499,
    discount: '40%Off',
    rating: 4,
    reviews: 344657,
  },
  {
    id: '20',
    image: require('../assets/images/MaskGroup2.png'),
    name: `Mammon Women's Handba (Set of 3, Beige)`,
    price: 999,
    oldPrice: 1999,
    discount: '50%Off',
    rating: 5,
    reviews: 646776,
  },
  {
    id: '21',
    image: require('../assets/images/MaskGroup3.png'),
    name: 'Do Bhai Women Wedges Sandal (Butterfly)',
    price: 1500,
    oldPrice: 3500,
    discount: '60%Off',
    rating: 4,
    reviews: 15007,
  },
  {
    id: '22',
    image: require('../assets/images/MaskGroup4.png'),
    name: 'Lakme Enrich Matte Lipstick - Shade RM1(4.7gm)',
    price: 1500,
    oldPrice: 3500,
    discount: '60%Off',
    rating: 4,
    reviews: 15007,
  },
];
